evo_config:
  _target_: shinka.core.EvolutionConfig
  patch_types:
    - "diff"
    - "full"
    - "cross"
  patch_type_probs:
    - 0.6
    - 0.3
    - 0.1
  num_generations: 100
  max_parallel_jobs: 5
  max_patch_resamples: 3
  max_patch_attempts: 3
  llm_models:
    - "local-Qwen/Qwen3-14B-AWQ-http://elisa:8765/v1/"
  llm_dynamic_selection: null
  llm_kwargs:
    max_tokens: 8192
  meta_rec_interval: 5
  meta_llm_models:
    - "local-Qwen/Qwen3-14B-AWQ-http://elisa:8765/v1/"
  embedding_model: "local-Qwen/Qwen2.5-7B-Instruct-AWQ-http://elisa:7654/v1/"
  results_dir: ${output_dir}
